### ISSUE TITLE
NFR: Configure analytics/tracking

### ISSUE THREAD

**Issue by Gonzalo-CG** [hlxsites/vg-macktrucks-com-museum#7]
Configure analytics/tracking (GTM, FB Pixel if needed, and OneTrust)

This is part of the GoLive activities.

**Comment by Kannan-CM** [comment]
<script src="https://cdn.cookielaw.org/scripttemplates/otSDKStub.js"  type="text/javascript" charset="UTF-8" data-domain-script="75b18b13-cd28-4fd4-8b38-2f090b2696fd" ></script>
<script type="text/javascript">
function OptanonWrapper() { }
</script>
